config/routes.rb
Rails.application.routes.draw do
   devise_for :users, :controllers => {registrations: "registrations", sessions: "sessions", passwords: "passwords"}, path: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticate :user do
    root :to => 'dashboard#index'
    get '/setting' => 'dashboard#edit'
    post '/setting' => 'dashboard#update'
    post "download" => 'accounts#download'
    post "information_download" => 'informations#information_download'
    get "get_file" => 'accounts#get_file'
    get "download_abnormals" => 'abnormals#download'
    post "batch_destroy" => 'accounts#batch_destroy'
    post "batch_destroy_ab" => 'abnormals#batch_destroy'
    post "batch_destroy_files" => "upload_files#batch_destroy_files"
    post "destroy_informations" => 'informations#batch_destroy'
    post "batch_update" => 'informations#batch_update'
    resources :accounts
    resources :informations
    resources :abnormals
    resources :platforms
    post "destroy_platforms" => 'platforms#batch_destroy'
    post "batch_update_platforms" => 'platforms#batch_update'
    resources :download_logs, :import_logs
    get "delete_success" => "informations#delete_success"
    get "toggle_switch" => "setting#toggle_switch"
    get "toggle_file_switch" => "setting#toggle_file_switch"
    resources :upload_files
    get "download_files" => "upload_files#download_files"
  end
  get "import_data" => 'accounts#import_data'
  get "new_import_data" => 'informations#import_data'
  get "new_get_data" => "informations#new_get_data"
  get "new_update_data" => "informations#new_update_data"
  get "check" => "informations#check"
  get "get_data" => "informations#get_data"
  get "update_data" => "informations#update_data"
  get "import_abnormal" => "abnormals#import"

  get "import_platform" => "platforms#import"
  get "get_platform" => "platforms#get_data"
  get "update_platform" => "platforms#update_data"
  get "download_file" => "upload_files#download_file"
  get "download_txt_file" => "upload_files#download_txt_file"

  get "privacy_policy_setting" => "accounts#privacy_policy_setting"
  get "wait_button_setting" => "accounts#wait_button_setting"

  get "get_account" => "accounts#get_account"
  get "get_account_data_setting" => "accounts#get_account_data_setting"
end

app/models/upload_file.rb
class UploadFile < ApplicationRecord
  before_save :init_path
  enum file_type: {
    plist: 0,
    txt: 1
  }
  def init_path
    self.file_path = "#{Rails.root}/public/upload_files/#{file_name}"
  end

  def link
    "download_file?file_name=#{self.file_name}"
  end

  def links
    "download_files?file_name=#{self.file_name}"
  end
end

app/controllers/upload_files_controller.rb
class UploadFilesController < ApplicationController
  # require 'fileutils'
  skip_before_action :authenticate_user!, :only => [:download_file, :download_txt_file]

  def index
    @upload_files = params[:type] != 'txt' ? UploadFile.plist : UploadFile.txt

  end

  def destroy
    @upload_file = UploadFile.find_by_id params[:id]
    path_to_file = @upload_file&.file_path
    File.delete(path_to_file) if path_to_file && File.exist?(path_to_file)
    @upload_file.destroy
    redirect_to upload_files_path, notice:"成功删除!"
  end

  def batch_destroy_files
    @upload_files = UploadFile.where(id: params[:upload_file_ids].split(","))
    @upload_files.destroy_all
    respond_to do |format|
      format.json{
        render json: {
          message: "成功"
        }
      }
    end
  end

  def new
    if params[:type] != 'txt'
      @upload_file = UploadFile.plist.new
    else
      @upload_file = UploadFile.txt.new
    end
  end

  def create
    @file_type = params[:upload_file][:file_type] ==  "1" ? "txt" : "plist"
    @upload_file = UploadFile.new
    if params[:tasks_file].present?
      file = params[:tasks_file]
      if file.original_filename.split('.').last == @file_type
        file_name = uploadFile(params[:tasks_file])
        if UploadFile.find_or_create_by(file_name: file_name, file_type: @file_type)
          redirect_to upload_files_path(type: @file_type), notice: "上传成功！"
        else
          redirect_to upload_files_path, notice: @upload_file.errors.full_messages.to_sentence
        end
      else
        redirect_to upload_files_path(type: @file_type), notice: "约定好的文件格式为 XXX.#{@file_type}"
      end
    else
      redirect_to upload_files_path(type: @file_type), notice: "上传有误，请检查数据重新上传！"
    end
  end

  def download_files
    @upload_file = UploadFile.find_by_file_name params[:file_name]
    if @upload_file&.file_path.present?
      send_file(@upload_file.file_path)
    else
      render json: {message: "文件不存在"}
    end
  end

  def download_file
    if Setting.first.file_switch
      @upload_file = UploadFile.find_by_file_name params[:file_name]
      if @upload_file&.file_path.present?
        send_file(@upload_file.file_path)
      else
        render json: {message: "文件不存在"}
      end
    else
      render json: {message: "当前不可获取文件"}
    end
  end

  def download_txt_file
    @upload_file = UploadFile.find_by_file_name params[:file_name]
    if @upload_file&.file_path.present? && @upload_file&.txt?
      send_file(@upload_file.file_path)
    else
      render json: {message: "文件不存在"}
    end
  end

  def uploadFile(file)
    if !file.original_filename.empty?
      @filename = getFileName(file.original_filename)
      FileUtils.mkdir_p File.join("#{Rails.root}/public/upload_files")
      File.open("#{Rails.root}/public/upload_files/#{@filename}", "wb") do |f|
        f.write(file.read)
      end
      return @filename
    end

  end

  def getFileName(filename)
    if !filename.nil?
      return filename
    end
  end

end

app/views/upload_files/index.html.erb
<% title =  params[:type] != "txt" ? "系统文件" : "脚本配置文件" %>
<% provide(:title, title) %>
<h1 class="page-header"><%= title %></h1>
<div class="table-responsive">
  <%= link_to "上传#{title}", new_upload_file_path(type: params[:type]), class: 'btn btn-success floatLeft' %>
  <% if params[:type] != "txt" %>
    <div class="testswitch">
      <input class="testswitch-checkbox" id="onoffswitch" type="checkbox" data-checked="<%= Setting.first.file_switch %>" >
      <label class="testswitch-label" for="onoffswitch">
        <span class="testswitch-inner" data-on="ON" data-off="OFF"></span>
        <span class="testswitch-switch"></span>
      </label>
    </div>
    <h4 class="tips">当前不能获取文件</h4>
  <% else %>
    <div class="testswitch">
      <input class="testswitch-checkbox" id="nonoffswitch" type="checkbox" data-checked="<%= Setting.first.wait_button %>" >
      <label class="testswitch-label" for="nonoffswitch">
        <span class="testswitch-inner" data-on="ON" data-off="OFF"></span>
        <span class="testswitch-switch"></span>
      </label>
    </div>
    <h4 class="tips">获取验证码是否等待2分钟</h4>
  <% end %>

</div>
<hr>

<% if @upload_files.any? %>
  <div class="row-fluid">
    <div class="span6">
      <p>
        <%= link_to 'javascript::void(0)', :data => {:toggle => :checkboxes, :action => :check, :range => 'true'} do %>
          <i class="glyphicon glyphicon-ok text-success"> </i>全选
        <% end %>

        <span> / </span>

        <%= link_to 'javascript::void(0)', :data => {:toggle => :checkboxes, :action => :uncheck, :range => 'true'} do %>
          <i class="glyphicon glyphicon-remove text-danger"> </i>全不选
        <% end %>

        <span> / </span>

        <%= link_to 'javascript::void(0)', :data => {:toggle => :checkboxes, :action => :toggle, :range => 'true'} do %>
          <i class="glyphicon glyphicon-refresh text-warning"> </i>反选
        <% end %>

        <%= link_to "javascript:void(0)", id: 'downloads', target: '_blank', class: "hide"  do %>
          <i class="glyphicon glyphicon-download-alt text-primary"> </i>导出？
        <% end %>

        <span> / </span>

        <%= link_to "#", id: 'batch_destroy' do %>
          <i class="glyphicon glyphicon-trash text-primary"> </i>删除选中
        <% end %>
      </p>
    </div>
  </div>
  <hr>

  <h3>文件总量：<%= @upload_files.count %></h3>
  <hr>
  <table class="table table-hover table-responsive">
    <thead>
      <tr>
        <th width="2%"></th>
        <th>文件</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @upload_files.each do |upload_file| %>
      <tr>
        <td>
          <label>
            <%= check_box_tag "upload_file_ids[#{upload_file.id}]", upload_file.id, false, :class => 'ace ace-checkbox-1 upload-file-checkbox' %>
            <span class="lbl"> </span>
          </label>
        </td>

        <td><%= upload_file.file_name %></td>
        <td>
          <%= link_to '下载', upload_file.links, target: '_blank', class: 'btn btn-info' %>
          <%= link_to '删除', upload_file_path(upload_file.id), class: 'btn btn-danger', data:{confirm: '确定删除吗?'}, method: :delete %>
        </td>

      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<script>
  $(document).ready(function() {
    $('[data-toggle=checkboxes][data-action=check]').click(function(e){
      e.preventDefault();
      $('.upload-file-checkbox').prop('checked', true)
      return false;
    });

    $('[data-toggle=checkboxes][data-action=uncheck]').click(function(e){
      e.preventDefault();
      $('.upload-file-checkbox').prop('checked', false)
      return false;
    });

    $('[data-toggle=checkboxes][data-action=toggle]').click(function(e){
      e.preventDefault();
      var checkboxes = $('.upload-file-checkbox');
      for(var i = 0; i<checkboxes.length; i++){
        var status = $(checkboxes[i]).prop('checked');
        $(checkboxes[i]).prop('checked', !status);
      }
      return false;
    });


    if($("#nonoffswitch").data("checked")){
      $("#nonoffswitch").prop('checked', true)
    }
    $("#nonoffswitch").on('click', function(){
      $.get("toggle_switch?wait_button=true")
    });

    if($("#onoffswitch").data("checked")){
      $("#onoffswitch").prop('checked', true)
      $('.tips').text("当前可以获取文件")
    }
    $("#onoffswitch").on('click', function(){
      clickSwitch()
      $.get("toggle_file_switch")
    });

    var clickSwitch = function() {
      if ($("#onoffswitch").is(':checked')) {
        console.log("在ON的状态下");
        $('.tips').text("当前可以获取文件")
      } else {
        console.log("在OFF的状态下");
        $('.tips').text("当前不可以获取文件")
      }
    };

    $("#batch_destroy").click(function () {
    var upload_file_ids = [];
    $.each($('.upload-file-checkbox:checked'), function () {
      upload_file_ids.push($(this).val());
    });

    if (upload_file_ids.length > 0) {
      $.ajax({
        url: "batch_destroy_files",
        method: 'POST',
        dataType: 'json',
        data: {upload_file_ids: upload_file_ids},
        success: function(res) {
          setTimeout(function(){
            window.location.reload()
          },2000);
        },
        error: function(error) {
          alert(error);
        }
      })
    } else {
      alert('你没有勾选任何帐号!');
      $("#batch_destroy").attr("href", "#")
    }
  })

  })
</script>

app/views/upload_files/new.html.erb
<% title =  params[:type] != "txt" ? "上传系统文件" : "上传脚本配置文件" %>
<% provide(:title, "#{title}") %>
<h1 class="page-header"></h1>

<div class="bs-example">
<%= simple_form_for @upload_file, url: upload_files_path, html: {multipart: true, class: 'form'} do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.hidden_field :file_type %>
  <div class="form-group">
    <label for="tasks_file">
    <%= "#{title}" %>
    <small>（请使用<%= params[:type] || "plist" %>文件格式。）</small>
    </label>
    <input type="file" name="tasks_file" id="tasks_file" class="form-control">
  </div>
  <%= f.submit "上传文件", :class => 'btn btn-success', 'data-disable-with' => '提交中...' %>
<% end %>
</div>