config/routes.rb
Rails.application.routes.draw do
   devise_for :users, :controllers => {registrations: "registrations", sessions: "sessions", passwords: "passwords"}, path: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticate :user do
    root :to => 'dashboard#index'
    get '/setting' => 'dashboard#edit'
    post '/setting' => 'dashboard#update'
    post "download" => 'accounts#download'
    post "information_download" => 'informations#information_download'
    get "get_file" => 'accounts#get_file'
    get "download_abnormals" => 'abnormals#download'
    post "batch_destroy" => 'accounts#batch_destroy'
    post "batch_destroy_ab" => 'abnormals#batch_destroy'
    post "batch_destroy_files" => "upload_files#batch_destroy_files"
    post "destroy_informations" => 'informations#batch_destroy'
    post "batch_update" => 'informations#batch_update'
    resources :accounts
    resources :informations
    resources :abnormals
    resources :platforms
    post "destroy_platforms" => 'platforms#batch_destroy'
    post "batch_update_platforms" => 'platforms#batch_update'
    resources :download_logs, :import_logs
    get "delete_success" => "informations#delete_success"
    get "toggle_switch" => "setting#toggle_switch"
    get "toggle_file_switch" => "setting#toggle_file_switch"
    resources :upload_files
    get "download_files" => "upload_files#download_files"
  end
  get "import_data" => 'accounts#import_data'
  get "new_import_data" => 'informations#import_data'
  get "new_get_data" => "informations#new_get_data"
  get "new_update_data" => "informations#new_update_data"
  get "check" => "informations#check"
  get "get_data" => "informations#get_data"
  get "update_data" => "informations#update_data"
  get "import_abnormal" => "abnormals#import"

  get "import_platform" => "platforms#import"
  get "get_platform" => "platforms#get_data"
  get "update_platform" => "platforms#update_data"
  get "download_file" => "upload_files#download_file"
  get "download_txt_file" => "upload_files#download_txt_file"

  get "privacy_policy_setting" => "accounts#privacy_policy_setting"
  get "wait_button_setting" => "accounts#wait_button_setting"

  get "get_account" => "accounts#get_account"
  get "get_account_data_setting" => "accounts#get_account_data_setting"
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:import, :get_data, :update_data]
  before_action :find_data, only: [ :edit, :update,:destroy]
  def index
    @platform = Platform.all
  end

  def destroy
    @data.destroy
    redirect_to platforms_path, notice:"成功删除!"
  end

  def batch_destroy
    @platform = Platform.where(id: params[:platform_ids])
    @platform.destroy_all
    respond_to do |format|
      format.json{
        render json: {
          message: "成功"
        }
      }
    end
  end

  def batch_update
    @platform = Platform.where(id: params[:platform_ids]).where(is_use: 1)
    @platform.update_all(is_use: 0)
    respond_to do |format|
      format.json{
        render json: {
          message: "待修改数据批量修改成功!"
        }
      }
    end
  end

   def import
    data = params[:data]

    @platform = Platform.new(data: data)
    rep = if @platform.save
            { code: 200, message: "导入成功！"}
          else
            { code: 404, message: @platform.errors.full_messages.to_sentence}
          end
    render :json => rep
  end

  def get_data
    @platform = Platform.where(is_use: 0).first

    begin
      rep = if @platform.present?
            @platform.update(is_use: 1)
            {
              code: 200,
              data: {id: @platform.id, token: @platform.data},
              message: "返回成功！"
            }
          else
            {
              code: 200,
              data: {status: false},
              message: "没有可用数据"
            }
          end
    rescue Exception => e
      {
        code: 404,
        data: {status: false},
        message: e
      }
    end
    render :json => rep
  end

  def update_data
    @data = Platform.find_by_id(params[:id])
    rep = if @data.present?
            if @data.update(is_use: 2)
              {
                code: 200,
                message: "更新成功"
              }
            else
              {
                code: 404,
                message: @data.errors.full_messages.to_sentence
              }
            end
          else
            {
              code: 404,
              message: "数据不存在"
            }
          end
    render :json => rep
  end

  def update
    @data = Platform.find(params[:id])
    if @data.update(is_use: 0)
      redirect_to platforms_path, notice: "更新成功!"
    else
      redirect_to platforms_path, alert: @data.errors.full_messages.to_sentence
    end
  end

  private
  def find_data
    @data = Platform.find(params[:id])
    rescue => e
     redirect_to platforms_path,alert:"没有找到数据!"
  end

end

app/views/platforms/index.html.erb
<% provide(:title, "东帝汶号码") %>
<h1 class="page-header">东帝汶号码</h1>

<hr>
<% if @platform.any? %>
  <div class="row-fluid">
    <div class="span6">
      <p>
        <%= link_to 'javascript::void(0);', :data => {:toggle => :checkboxes, :action => :check, :range => 'true'} do %>
          <i class="glyphicon glyphicon-ok text-success"> </i>全选
        <% end %>

        <span> / </span>

        <%= link_to 'javascript::void(0);', :data => {:toggle => :checkboxes, :action => :uncheck, :range => 'true'} do %>
          <i class="glyphicon glyphicon-remove text-danger"> </i>全不选
        <% end %>

        <span> / </span>

        <%= link_to 'javascript::void(0);', :data => {:toggle => :checkboxes, :action => :toggle, :range => 'true'} do %>
          <i class="glyphicon glyphicon-refresh text-warning"> </i>反选
        <% end %>

        <span> / </span>

        <%= link_to "#", id: 'batch_destroy' do %>
          <i class="glyphicon glyphicon-trash text-primary"> </i>删除选中
        <% end %>

        <span> / </span>

        <%= link_to "#", id: 'batch' do %>
          <i class="glyphicon glyphicon-download-alt text-primary"> </i>批量修改状态为未使用
        <% end %>
      </p>
    </div>
  </div>
  <hr>
  <h3>数据总量：<%= @platform.count %></h3>
  <hr>
  <table class="table table-hover table-responsive">
    <thead>
      <tr>
        <th width="5%"></th>
        <th width="60%">数据</th>
        <th width="10%">状态</th>
        <th width="25%">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @platform.each do |platform| %>
      <tr>
        <td>
          <label>
            <%= check_box_tag "platform_ids[#{platform.id}]", platform.id, false, :class => 'ace ace-checkbox-1 platform-checkbox' %>
            <span class="lbl"> </span>
          </label>
        </td>
        <td><%= platform.data %></td>
        <% if platform.is_use == 2 %>
          <td class="text-danger">注册成功</td>
        <% elsif platform.is_use == 1 %>
          <td class="text-info">使用中</td>
        <% else %>
           <td class="text-success">未使用</td>
        <% end %>
        <td>
          <%= link_to '改为未使用', platform_path(platform), class: 'btn btn-info', method: :put %>
          <%= link_to '删除', platform_path(platform), class: 'btn btn-danger', data:{confirm: '确定删除吗?'}, method: :delete %>

        </td>

      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<script>
  $('[data-toggle=checkboxes][data-action=check]').click(function(e){
    e.preventDefault();
    $('.platform-checkbox').prop('checked', true)
    return false;
  });

  $('[data-toggle=checkboxes][data-action=uncheck]').click(function(e){
    e.preventDefault();
    $('.platform-checkbox').prop('checked', false)
    return false;
  });

  $('[data-toggle=checkboxes][data-action=toggle]').click(function(e){
    e.preventDefault();
    var checkboxes = $('.platform-checkbox');
    for(var i = 0; i<checkboxes.length; i++){
      var status = $(checkboxes[i]).prop('checked');
      $(checkboxes[i]).prop('checked', !status);
    }
    return false;
  });


  $("#batch_destroy").click(function () {
    var platform_ids = [];
    $.each($('.platform-checkbox:checked'), function () {
      platform_ids.push($(this).val());
    });

    if (platform_ids.length > 0) {
      $.ajax({
        url: "destroy_platforms",
        method: 'POST',
        dataType: 'json',
        data: {platform_ids: platform_ids},
        success: function(res) {
          setTimeout(function(){
            window.location.reload()
          },2000);
        },
        error: function(error) {
          alert(error);
        }
      })
    } else {
      alert('你没有勾选任何帐号!');
      $("#batch_destroy").attr("href", "#")
    }
  })

  $("#batch").click(function () {
    var platform_ids = [];
    $.each($('.platform-checkbox:checked'), function () {
      platform_ids.push($(this).val());
    });

    if (platform_ids.length > 0) {
      $.ajax({
        url: "batch_update_platforms",
        method: 'POST',
        dataType: 'json',
        data: {platform_ids: platform_ids, new_import: "<%= params[:new_import] %>"},
        success: function(res) {
          alert(res.message)
          setTimeout(function(){
            window.location.reload()
          },2000);
        },
        error: function(error) {
          alert(error);
        }
      })
    } else {
      alert('你没有勾选任何帐号!');
      $("#batch").attr("href", "#")
    }
  });

</script>