config/routes.rb
Rails.application.routes.draw do
   devise_for :users, :controllers => {registrations: "registrations", sessions: "sessions", passwords: "passwords"}, path: 'user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticate :user do
    root :to => 'dashboard#index'
    get '/setting' => 'dashboard#edit'
    post '/setting' => 'dashboard#update'
    post "download" => 'accounts#download'
    post "information_download" => 'informations#information_download'
    get "get_file" => 'accounts#get_file'
    get "download_abnormals" => 'abnormals#download'
    post "batch_destroy" => 'accounts#batch_destroy'
    post "batch_destroy_ab" => 'abnormals#batch_destroy'
    post "batch_destroy_files" => "upload_files#batch_destroy_files"
    post "destroy_informations" => 'informations#batch_destroy'
    post "batch_update" => 'informations#batch_update'
    resources :accounts
    resources :informations
    resources :abnormals
    resources :platforms
    post "destroy_platforms" => 'platforms#batch_destroy'
    post "batch_update_platforms" => 'platforms#batch_update'
    resources :download_logs, :import_logs
    get "delete_success" => "informations#delete_success"
    get "toggle_switch" => "setting#toggle_switch"
    get "toggle_file_switch" => "setting#toggle_file_switch"
    resources :upload_files
    get "download_files" => "upload_files#download_files"
  end
  get "import_data" => 'accounts#import_data'
  get "new_import_data" => 'informations#import_data'
  get "new_get_data" => "informations#new_get_data"
  get "new_update_data" => "informations#new_update_data"
  get "check" => "informations#check"
  get "get_data" => "informations#get_data"
  get "update_data" => "informations#update_data"
  get "import_abnormal" => "abnormals#import"

  get "import_platform" => "platforms#import"
  get "get_platform" => "platforms#get_data"
  get "update_platform" => "platforms#update_data"
  get "download_file" => "upload_files#download_file"
  get "download_txt_file" => "upload_files#download_txt_file"

  get "privacy_policy_setting" => "accounts#privacy_policy_setting"
  get "wait_button_setting" => "accounts#wait_button_setting"

  get "get_account" => "accounts#get_account"
  get "get_account_data_setting" => "accounts#get_account_data_setting"
end

app/models/information.rb
class Information < ApplicationRecord
  scope :list2, -> { where(list_num: 2) }
  scope :default, -> { where(list_num: 1) }
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:get_data, :update_data,:import_data, :new_get_data, :new_update_data, :check]
  before_action :find_data, only: [ :edit, :update,:destroy]
  def index
    @informations = if params[:new_import].present?
                      Information.where(account: nil)
                    else
                      Information.where(phone: nil)
                    end
    @informations = params[:list2] ? @informations.list2 :  @informations.default
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new
    errors = []
    list_num = params[:list2] ? 2 : 1
    if params[:tasks_file].present?
      file = params[:tasks_file]
      if file.original_filename.split('.').last == 'txt'
        datas = []
        File.open(file.path).each do |line|
          account, link = line.split("----")
          datas << {account: account, link: link.chomp, list_num: list_num} if account.present? && link.present?
        end
        if datas.present?
          begin
            ActiveRecord::Base.transaction do
              Information.import datas
            end
          rescue Exception => e
            redirect_to informations_path(list2: params[:list2]), notice: e
          end

          redirect_to informations_path(list2: params[:list2]), notice: "上传成功！"
        else
          redirect_to informations_path(list2: params[:list2]), notice: "没有数据"
        end

      else
        redirect_to informations_path(list2: params[:list2]), notice: "约定好的文件格式为 XXX.txt"
      end
    else
      redirect_to informations_path(list2: params[:list2]), notice: "上传有误，请检查数据重新上传！"
    end
  end

  def destroy
    link = @data.phone.present? ? informations_path(new_import: true) : informations_path(list2: @data.list_num == 2 ? true : nil)
    @data.destroy
    redirect_to link, notice:"成功删除!"
  end

  def information_download
    @informations = Information.where(id: params[:information_ids].split(","))

    output = ''
    if params[:new_import].present?
      @informations.pluck(:phone, :password ).each do |information|
        output << information.join("----")
        output << "\n"
      end
    else
      @informations.pluck(:account, :link ).each do |information|
        output << information.join("----")
        output << "\n"
      end
    end
    path = "#{Rails.root}/log/informations-#{Time.now.strftime('%Y-%m-%d-%H-%M-%S')}.txt"
    file = File.open(path, 'a')
    file.write(output)

    file.close

    respond_to do |format|
      format.json{
        render json: {
          path: path
        }
      }
    end
  end

  def batch_destroy
    @informations = Information.where(id: params[:information_ids])
    @informations.destroy_all
    respond_to do |format|
      format.json{
        render json: {
          message: "成功"
        }
      }
    end
  end

  def batch_update
    if params[:new_import].present?
      @informations = Information.where(id: params[:information_ids]).where.not(is_use: 2)
    else
      @informations = Information.where(id: params[:information_ids]).where(is_use: 1)
    end
    @informations.update_all(is_use: 0)
    respond_to do |format|
      format.json{
        render json: {
          message: "待修改数据批量修改成功!"
        }
      }
    end
    # redirect_to informations_path, notice:"待修改数据批量修改成功!"
  end

  def delete_success
    if params[:new_import].present?
      Information.where(is_use: 2, account: nil).destroy_all
      @link = informations_path(new_import: true)
    else
      Information.where(is_use: 2, phone: nil).destroy_all
      @link = informations_path
    end

    redirect_to @link, notice:"批量操作成功!"
  end

  def get_data
    if (validation = params[:validation].present?)
      @information = Information.where(is_use: 1, phone: nil, list_num:( params[:list2] ? 2 : 1)).first
    else
      @information = Information.where(is_use: 0, phone: nil, list_num:( params[:list2] ? 2 : 1)).first
    end

    begin

      rep = if !(params[:list2] ? Setting.first.list_switch : Setting.first.switch)
            {
              code: 200,
              data: {status: false},
              message: "等待开启数据获取"
            }
          elsif @information.present?
            @information.update(is_use: (validation ? 3 : 1))
            {
              code: 200,
              data: {id: @information.id, account: @information.account, link: @information.link, status: true },
              message: "返回成功！"
            }
          else
            {
              code: 200,
              data: {status: false},
              message: "没有可用数据"
            }
          end
    rescue Exception => e
      rep = {
        code: 404,
        data: {status: false},
        message: e
      }
    end
    render :json => rep
  end

  def update_data
    @data = Information.find_by_id(params[:id])
    rep = if @data.present?

            if @data.update(is_use: 2)
              {
                code: 200,
                message: "更新成功"
              }
            else
              {
                code: 404,
                message: @data.errors.full_messages.to_sentence
              }
            end
          else
            {
              code: 404,
              message: "数据不存在"
            }
          end
    render :json => rep
  end

  def check
    @arr = ["未使用", "二维码获取成功", "完成", "使用中"]
    @data = Information.find_by_id(params[:id])
    rep = if @data.present?
        {
          code: 200,
          message: @arr[@data.is_use]
        }
    else
      {
        code: 404,
        message: "数据不存在"
      }
    end
render :json => rep
  end

  def new_get_data

    @information = Information.where(is_use: 0, account: nil).first

    begin

      rep = if @information.present?
            @information.update(is_use: 3)
            {
              code: 200,
              data: {id: @information.id, phone: @information.phone, password: @information.password, status: true },
              message: "返回成功！"
            }
          else
            {
              code: 200,
              data: {status: false},
              message: "没有可用数据"
            }
          end
    rescue Exception => e
      {
        code: 404,
        data: {status: false},
        message: e
      }
    end
    render :json => rep
  end

  def new_update_data
    @data = Information.find_by_id(params[:id])
    rep = if @data.present?
            is_use = params[:success].present? ? 2 : 1
            if @data.update(is_use: is_use)
              {
                code: 200,
                message: "更新成功:#{params[:success].present? ? '完成' : '二维码获取成功'}"
              }
            else
              {
                code: 404,
                message: @data.errors.full_messages.to_sentence
              }
            end
          else
            {
              code: 404,
              message: "数据不存在"
            }
          end
    render :json => rep
  end


  def update
    @data = Information.find(params[:id])
    link = @data.phone.present? ? informations_path(new_import: true) : informations_path(list2: @data.list_num == 2 ? true : nil)
    if @data.update(is_use: 0)
      redirect_to link, notice: "更新成功!"
    else
      redirect_to link, alert: @data.errors.full_messages.to_sentence
    end
  end

  def import_data
    phone = params[:phone]
    password = params[:password]

    @information = Information.new(phone: phone, password: password)
    rep = if @information.save
            { code: 200, message: "上传成功", data: {id: @information.id}}
          else
            { code: 404, message: @information.errors.full_messages.to_sentence}
          end
    render :json => rep
  end

  private
  def find_data
    @data = Information.find(params[:id])
    rescue => e
     redirect_to informations_path,alert:"没有找到数据!"
  end

end

app/views/informations/_form.html.erb
<%= render 'shared/error_messages', object: f.object %>


<div class="form-group">
  <label for="tasks_file">
  导入数据 <small>（请使用固定数据格式。）</small>
  </label>
  <input type="file" name="tasks_file" id="tasks_file" class="form-control">
</div>

app/views/informations/index.html.erb
<% title = params[:new_import].present? ? "获取二维码帐号列表" : "导入数据"  %>
<% title = params[:list2] ? "导入数据2" : title %>
<% del_title = params[:new_import].present? ? "获取二维码帐号成功帐号删除" : "注册成功帐号删除"  %>
<% provide(:title, title) %>
<h1 class="page-header"><%= title %></h1>

<% unless params[:new_import].present? %>
  <div class="table-responsive" >
    <%= link_to title, new_information_path(list2: params[:list2]), class: 'btn btn-success floatLeft' %>

    <div class="testswitch floatLeft" >
      <input class="testswitch-checkbox" id="onoffswitch" type="checkbox" data-checked="<%= params[:list2] ? Setting.first.list_switch : Setting.first.switch %>" >
      <label class="testswitch-label" for="onoffswitch">
        <span class="testswitch-inner" data-on="ON" data-off="OFF"></span>
        <span class="testswitch-switch"></span>
      </label>
    </div>
    <div class="floatLeft">
      <h4 class="tips floatLeft">当前不能获取数据</h4>
    </div>
    <div class="floatLeft">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
    <% unless params[:list2] %>
      <div class="testswitch floatLeft">
        <input class="testswitch-checkbox" id="nonoffswitch" type="checkbox" data-checked="<%= Setting.first.privacy_policy %>" >
        <label class="testswitch-label" for="nonoffswitch">
          <span class="testswitch-inner" data-on="ON" data-off="OFF"></span>
          <span class="testswitch-switch"></span>
        </label>
      </div>
      <div class="floatLeft">
        <h4>隐秘政策等待</h4>
      </div>
    <% end %>
  </div>
  <hr>
<% end %>
<% if @informations.any? %>
  <div class="row-fluid">
    <div class="span6">
      <p>
        <%= link_to 'javascript::void(0);', :data => {:toggle => :checkboxes, :action => :check, :range => 'true'} do %>
          <i class="glyphicon glyphicon-ok text-success"> </i>全选
        <% end %>

        <span> / </span>

        <%= link_to 'javascript::void(0);', :data => {:toggle => :checkboxes, :action => :uncheck, :range => 'true'} do %>
          <i class="glyphicon glyphicon-remove text-danger"> </i>全不选
        <% end %>

        <span> / </span>

        <%= link_to 'javascript::void(0);', :data => {:toggle => :checkboxes, :action => :toggle, :range => 'true'} do %>
          <i class="glyphicon glyphicon-refresh text-warning"> </i>反选
        <% end %>

        <span> / </span>

        <%= link_to 'javascript:void(0)', id: 'download' do %>
          <i class="glyphicon glyphicon-download-alt text-primary"> </i>导出
        <% end %>

        <%= link_to "javascript:void(0)", id: 'downloads', target: '_blank', class: "hide"  do %>
          <i class="glyphicon glyphicon-download-alt text-primary"> </i>导出？
        <% end %>

        <span> / </span>

        <%= link_to "#", id: 'batch_destroy' do %>
          <i class="glyphicon glyphicon-trash text-primary"> </i>删除选中
        <% end %>

        <span> / </span>

        <%= link_to "#", id: 'batch' do %>
          <i class="glyphicon glyphicon-download-alt text-primary"> </i>批量修改状态为未使用
        <% end %>

        <span> / </span>

        <%= link_to delete_success_path(new_import: params[:new_import]), id: 'delete_success' do %>
          <i class="glyphicon glyphicon-download-alt text-primary"> </i>注册成功帐号删除
        <% end %>
      </p>
    </div>
  </div>
  <hr>
  <h3>数据总量：<%= @informations.count %></h3>
  <% if params[:new_import].present? %>
    <h3>成功数据总量：<%= @informations.where(is_use: 2).count %></h3>
  <% end %>
  <hr>
  <table class="table table-hover table-responsive">
    <thead>
      <tr>
        <th width="5%"></th>
        <th width="15%"> 帐号</th>
        <th width="50%"><%= params[:new_import].present? ? "密码" : "链接" %></th>
        <th width="10%">状态</th>
        <th width="20%">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @informations.each do |information| %>
        <% if params[:new_import].nil? %>
          <tr>
            <td>
              <label>
                <%= check_box_tag "information_ids[#{information.id}]", information.id, false, :class => 'ace ace-checkbox-1 information-checkbox' %>
                <span class="lbl"> </span>
              </label>
            </td>
            <td><%= information.account %></td>
            <td class="hidden_text"><%= information.link %></td>
            <% if information.is_use == 2 %>
              <td class="text-primary">注册成功</td>
            <% elsif information.is_use == 1 %>
              <td class="text-info">待修改</td>
            <% elsif information.is_use == 3 %>
              <td class="text-danger">验证中</td>
            <% else %>
              <td class="text-success">未使用</td>
            <% end %>
            <td>
              <%= link_to '改为未使用', information_path(information), class: 'btn btn-info', method: :put %>
              <%= link_to '删除', information_path(information), class: 'btn btn-danger', data:{confirm: '确定删除吗?'}, method: :delete %>

            </td>

          </tr>
        <% else %>
          <tr>
            <td>
              <label>
                <%= check_box_tag "information_ids[#{information.id}]", information.id, false, :class => 'ace ace-checkbox-1 information-checkbox' %>
                <span class="lbl"> </span>
              </label>
            </td>
            <td><%= information.phone %></td>
            <td class="hidden_text"><%= information.password %></td>
            <% if information.is_use == 2 %>
              <td class="text-primary">完成</td>
            <% elsif information.is_use == 1 %>
              <td class="text-info">二维码获取成功</td>
            <% elsif information.is_use == 3 %>
              <td class="text-danger">使用中</td>
            <% else %>
              <td class="text-success">未使用</td>
            <% end %>
            <td>
              <%= link_to '改为未使用', information_path(information, new_import: true), class: 'btn btn-info', method: :put %>
              <%= link_to '删除', information_path(information, new_import: true), class: 'btn btn-danger', data:{confirm: '确定删除吗?'}, method: :delete %>

            </td>

          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>
<script>
  $('[data-toggle=checkboxes][data-action=check]').click(function(e){
    e.preventDefault();
    $('.information-checkbox').prop('checked', true)
    return false;
  });

  $('[data-toggle=checkboxes][data-action=uncheck]').click(function(e){
    e.preventDefault();
    $('.information-checkbox').prop('checked', false)
    return false;
  });

  $('[data-toggle=checkboxes][data-action=toggle]').click(function(e){
    e.preventDefault();
    var checkboxes = $('.information-checkbox');
    for(var i = 0; i<checkboxes.length; i++){
      var status = $(checkboxes[i]).prop('checked');
      $(checkboxes[i]).prop('checked', !status);
    }
    return false;
  });

  $("#download").click(function () {
    var information_ids = [];
    $.each($('.information-checkbox:checked'), function () {
      information_ids.push($(this).val());
    });
    if (information_ids.length > 0) {
      $.ajax({
        url: "information_download",
        method: 'POST',
        dataType: 'json',
        data: {information_ids: information_ids, new_import: "<%= params[:new_import] %>"},
        success: function(res) {
          $("#downloads").attr("href", "get_file?path=" + res.path)
          $("#downloads").append("<span></span>");
          $("#downloads span").click();
          $("#downloads").click()
          setTimeout(function(){
            window.location.reload()
          },2000);
        },
        error: function(error) {
          alert(error);
        }
      })
    } else {
      alert('你没有勾选任何帐号!');
    }
  });
  $("#batch_destroy").click(function () {
    var information_ids = [];
    $.each($('.information-checkbox:checked'), function () {
      information_ids.push($(this).val());
    });

    if (information_ids.length > 0) {
      $.ajax({
        url: "destroy_informations",
        method: 'POST',
        dataType: 'json',
        data: {information_ids: information_ids},
        success: function(res) {
          setTimeout(function(){
            window.location.reload()
          },2000);
        },
        error: function(error) {
          alert(error);
        }
      })
    } else {
      alert('你没有勾选任何帐号!');
      $("#batch_destroy").attr("href", "#")
    }
  })

  $("#batch").click(function () {
    var information_ids = [];
    $.each($('.information-checkbox:checked'), function () {
      information_ids.push($(this).val());
    });

    if (information_ids.length > 0) {
      $.ajax({
        url: "batch_update",
        method: 'POST',
        dataType: 'json',
        data: {information_ids: information_ids, new_import: "<%= params[:new_import] %>"},
        success: function(res) {
          alert(res.message)
          setTimeout(function(){
            window.location.reload()
          },2000);
        },
        error: function(error) {
          alert(error);
        }
      })
    } else {
      alert('你没有勾选任何帐号!');
      $("#batch").attr("href", "#")
    }
  });

$(document).ready(function() {
  if($("#onoffswitch").data("checked")){
    $("#onoffswitch").prop('checked', true)
    $('.tips').text("当前可以获取数据")
  }
  $("#onoffswitch").on('click', function(){
		clickSwitch()
    $.get("toggle_switch<%= params[:list2] ?  '?list2=true' : '' %>")
	});


  if($("#nonoffswitch").data("checked")){
    $("#nonoffswitch").prop('checked', true)
  }
  $("#nonoffswitch").on('click', function(){
    $.get("toggle_switch?privacy_policy=true")
	});

	var clickSwitch = function() {
		if ($("#onoffswitch").is(':checked')) {
			console.log("在ON的状态下");
      $('.tips').text("当前可以获取数据")
		} else {
			console.log("在OFF的状态下");
      $('.tips').text("当前不可以获取数据")
		}
	};
});

</script>

app/views/informations/new.html.erb
<% provide(:title, '导入数据') %>
<h1 class="page-header">导入数据</h1>

<div class="bs-example">
<%= simple_form_for @information, url: informations_path(list2: params[:list2]), html: {multipart: true, class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '导入数据', :class => 'btn btn-success', 'data-disable-with' => '提交中...' %>
<% end %>
</div>